language: node_js
node_js:
  - stable
  - 6

# Use containers.
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
